### ISSUE TITLE
Mcmmo doesnt show up in modules

### ISSUE THREAD

**Issue by alexanderb25** [Browsit/mcMMOQuestsModule#3]
Hello, 

So basically ive installed the jar file into the "Plugins/Quests/modules" directory and have restarted and reloaded the server multiple times and it doesn't show up under the "custom objectives" modules tab.

Any idea what might be wrong?

Thanks

**Comment by PikaMug** [comment]
This module does not offer any Objectives. It offers one Reward and one Requirement.

**Comment by alexanderb25** [comment]
Thanks man appreciate the response, maybe in future if you start the project up again, you should try and make it so you can make players gain mcmmo skill levels and experience as part of the quests.
