### ISSUE TITLE
McMMO Skill Level rewards are not granted

### ISSUE THREAD

**Issue by HorusApl** [Browsit/mcMMOQuestsModule#6]
For any quest, if a rewards details-override is set which is supposed to be just cosmetic, it will not grant any skill/xp rewards to the player. If no details override is set, the skill rewards are given without issue.

**Comment by PikaMug** [comment]
~~I was not able to replicate this using latest development build of Quests and mcMMO Overhaul v2.2.018 on a Paper 1.21 server. Please reply with your versions and an example quest if you'd like me to explore this further.~~

**Edit:** Nevermind, I made a mistake during testing. Looking into this now.

**Comment by PikaMug** [comment]
This turned out to be an issue with Quests itself. Please try the following development build:
https://ci.codemc.io/job/PikaMug/job/Quests/503/
